site_name: anytime
site_url: https://github.com/eddelbuettel/anytime

## input directory, usually 'docs' which we use for output
docs_dir: src
## output directory, i.e. docs/ on a GH repo
## has to be a subdirectory so need to then copy to ../docs
site_dir: docs

theme:
  name: material
  custom_dir: overrides
#  palette:
#    scheme: default
#    primary: blue grey
#    accent: grey
  features:
    - tabs
  font:
#    text: Source Sans Pro
    text: Lato
#    text: Oswald
#    code: Roboto Mono
  favicon: assets/Rlogo.png
  logo: assets/Rlogo.svg

extra_css:
  - assets/extra.css

extra:
  social:
    #- icon: fontawesome/brands/twitter
    #  link: https://twitter.com/eddelbuettel
    - icon: fontawesome/brands/github
      link: https://github.com/eddelbuettel/nanotime

nav:
  - Home:
    - index.md
  - Reference:
    - man/anytime-package.md
    - man/anytime.md
    - man/assertDate.md
    - man/getFormats.md
    - man/iso8601.md
  - Articles:
    - Introductory Vignette: vignette.md
  - News:
    - news.md
  - Changelog:
    - changelog.md
